version: '3'
services:
  postgres-server:
    image: i2gy/remote-test-reporter-database:2.2
    environment:
     - POSTGRES_PASSWORD=pass
  api-server:
    image: i2gy/remote-test-reporter-server:2.2
    ports:
      - "8000:8000"
    environment:
      - db_address=postgres-server
      - db_port=5432
      - admin_username=user
      - admin_password=password
    restart: always
  frontend:
    image: i2gy/remote-test-reporter-frontend:2.2
    ports:
      - "5000:5000"
    environment:
      - admin_username=user
      - admin_password=password
      - username=user
      - password=password
      - backend_url=http://api-server:8000/
    restart: always
    
