version: '3'
services:
  postgres-server:
    image: rtr-db:1.0
    environment:
     - POSTGRES_PASSWORD=pass
  api-server:
    image: rtr-server:1.0
    ports:
      - "8000:8000"
    environment:
      - db_address=postgres-server
      - db_port=5432
      - admin_username=user
      - admin_password=password
    restart: always
  frontend:
    image: rtr-frontend:1.0
    ports:
      - "5000:5000"
    environment:
      - admin_username=user
      - admin_password=password
      - username=user
      - password=password
      - backend_url=http://api-server:8000/
    restart: always
